/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void drawFlightControlWindow(PApplet appc, GWinData data) { //_CODE_:flightCommandWindow:442412:
  appc.background(230);
} //_CODE_:flightCommandWindow:442412:

public void startButtonClicked(GButton source, GEvent event) { //_CODE_:startButton:752526:
  if (started == false) { 
    running = true;
  }
  
  if (!planes.isEmpty()) {
    started = !started;
  }
} //_CODE_:startButton:752526:

public void clearButtonClicked(GButton source, GEvent event) { //_CODE_:clearFlights:877504:
  planes.clear();
  started = false;
} //_CODE_:clearFlights:877504:

public void departureSelected(GDropList source, GEvent event) { //_CODE_:departureList:786137:
  int selectedIndex = departureList.getSelectedIndex();
  departure = airports.get(selectedIndex);
} //_CODE_:departureList:786137:

public void arrivalSelected(GDropList source, GEvent event) { //_CODE_:arrivalList:423776:
  int selectedIndex = arrivalList.getSelectedIndex();
  arrival = airports.get(selectedIndex);

} //_CODE_:arrivalList:423776:

public void addPlanetoMap(GButton source, GEvent event) { //_CODE_:addPlane:926160:
  
  if (departure != arrival) {
    if (planes.size() < 8) {
      String planeimg = "plane_" + planes.size() + ".png";
      Plane p1 = new Plane(departure, arrival, planeimg);
      planes.add(p1);
    }
  }
} //_CODE_:addPlane:926160:

public void updateInfo(GTextArea source, GEvent event) { //_CODE_:informationBox:375751:
  println("informationBox - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:informationBox:375751:

public void pauseButtonClicked(GButton source, GEvent event) { //_CODE_:pauseButton:377502:
  running = !running;
  
  if (running == false) {
   pauseButton.setText("CONTINUE");
  }
  else {
    pauseButton.setText("PAUSE");
  }
} //_CODE_:pauseButton:377502:

public void panel1_Click1(GPanel source, GEvent event) { //_CODE_:panel1:326748:
  println("panel1 - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:panel1:326748:

synchronized public void createPlaneWindow(PApplet appc, GWinData data) { //_CODE_:PlaneWindow:600548:
  appc.background(230);
} //_CODE_:PlaneWindow:600548:

public void pathVisibilityChanged(GCheckbox source, GEvent event) { //_CODE_:togglePath:714996:
  selectedPlane.showPath = !selectedPlane.showPath;
} //_CODE_:togglePath:714996:

public void trailVisibilityChanged(GCheckbox source, GEvent event) { //_CODE_:toggleTrail:827319:
  selectedPlane.showTrail = !selectedPlane.showTrail;

} //_CODE_:toggleTrail:827319:

public void searchRVisibilityChanged(GCheckbox source, GEvent event) { //_CODE_:toggleR:845871:
  selectedPlane.showRadius = !selectedPlane.showRadius;
} //_CODE_:toggleR:845871:

public void planeVisibilityChanged(GCheckbox source, GEvent event) { //_CODE_:togglePlane:731911:
  selectedPlane.visible = !selectedPlane.visible;
} //_CODE_:togglePlane:731911:

public void speedChanged(GSlider source, GEvent event) { //_CODE_:speedSlider:770580:
  selectedPlane.speed = speedSlider.getValueF();
} //_CODE_:speedSlider:770580:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("ARROWPLANE");
  flightCommandWindow = GWindow.getWindow(this, "Flight Command Window", 0, 0, 350, 600, JAVA2D);
  flightCommandWindow.noLoop();
  flightCommandWindow.setActionOnClose(G4P.KEEP_OPEN);
  flightCommandWindow.addDrawHandler(this, "drawFlightControlWindow");
  startButton = new GButton(flightCommandWindow, 20, 80, 80, 30);
  startButton.setText("START");
  startButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  startButton.addEventHandler(this, "startButtonClicked");
  label1 = new GLabel(flightCommandWindow, 20, 50, 149, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("SIMULATION CONTROLS");
  label1.setOpaque(false);
  clearFlights = new GButton(flightCommandWindow, 110, 80, 111, 30);
  clearFlights.setText("CLEAR FLIGHTS");
  clearFlights.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  clearFlights.addEventHandler(this, "clearButtonClicked");
  label2 = new GLabel(flightCommandWindow, 20, 130, 230, 20);
  label2.setText("PLANE CONTROLS");
  label2.setOpaque(false);
  label3 = new GLabel(flightCommandWindow, 20, 160, 115, 20);
  label3.setText("Departure Airport:");
  label3.setOpaque(false);
  label4 = new GLabel(flightCommandWindow, 20, 190, 80, 20);
  label4.setText("Arrival Airport");
  label4.setOpaque(false);
  departureList = new GDropList(flightCommandWindow, 140, 160, 180, 220, 10, 10);
  departureList.setItems(loadStrings("list_786137"), 0);
  departureList.addEventHandler(this, "departureSelected");
  arrivalList = new GDropList(flightCommandWindow, 140, 190, 180, 220, 10, 10);
  arrivalList.setItems(loadStrings("list_423776"), 0);
  arrivalList.addEventHandler(this, "arrivalSelected");
  addPlane = new GButton(flightCommandWindow, 20, 220, 100, 30);
  addPlane.setText("ADD PLANE");
  addPlane.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  addPlane.addEventHandler(this, "addPlanetoMap");
  informationBox = new GTextArea(flightCommandWindow, 20, 300, 310, 180, G4P.SCROLLBARS_NONE);
  informationBox.setPromptText("Select a Plane or Weather Event to see it's information :)");
  informationBox.setOpaque(true);
  informationBox.addEventHandler(this, "updateInfo");
  label5 = new GLabel(flightCommandWindow, 20, 270, 240, 20);
  label5.setText("COMMUNICATION PANEL");
  label5.setOpaque(false);
  pauseButton = new GButton(flightCommandWindow, 230, 80, 90, 30);
  pauseButton.setText("PAUSE");
  pauseButton.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  pauseButton.addEventHandler(this, "pauseButtonClicked");
  panel1 = new GPanel(flightCommandWindow, 360, 60, 100, 80, "Tab bar text");
  panel1.setText("Tab bar text");
  panel1.setOpaque(true);
  panel1.addEventHandler(this, "panel1_Click1");
  PlaneWindow = GWindow.getWindow(this, "Configure Flight Metrics", 1350, 0, 200, 300, JAVA2D);
  PlaneWindow.noLoop();
  PlaneWindow.setActionOnClose(G4P.CLOSE_WINDOW);
  PlaneWindow.addDrawHandler(this, "createPlaneWindow");
  selectedPlaneTitle = new GLabel(PlaneWindow, 8, 8, 176, 60);
  selectedPlaneTitle.setText("selectedPlaneName");
  selectedPlaneTitle.setOpaque(false);
  label6 = new GLabel(PlaneWindow, 8, 72, 176, 20);
  label6.setText("Increase Base Speed:");
  label6.setOpaque(false);
  togglePath = new GCheckbox(PlaneWindow, 10, 170, 184, 20);
  togglePath.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  togglePath.setText("Toggle path visibility");
  togglePath.setOpaque(false);
  togglePath.addEventHandler(this, "pathVisibilityChanged");
  toggleTrail = new GCheckbox(PlaneWindow, 10, 200, 160, 20);
  toggleTrail.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  toggleTrail.setText("Toggle trail visibility");
  toggleTrail.setOpaque(false);
  toggleTrail.addEventHandler(this, "trailVisibilityChanged");
  toggleR = new GCheckbox(PlaneWindow, 8, 224, 160, 40);
  toggleR.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  toggleR.setText("Toggle search radius visibility");
  toggleR.setOpaque(false);
  toggleR.addEventHandler(this, "searchRVisibilityChanged");
  togglePlane = new GCheckbox(PlaneWindow, 10, 271, 152, 20);
  togglePlane.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  togglePlane.setText("Toggle plane visibility");
  togglePlane.setOpaque(false);
  togglePlane.addEventHandler(this, "planeVisibilityChanged");
  togglePlane.setSelected(true);
  speedSlider = new GSlider(PlaneWindow, 8, 104, 170, 56, 10.0);
  speedSlider.setShowValue(true);
  speedSlider.setShowLimits(true);
  speedSlider.setLimits(1.0, 0.5, 5.0);
  speedSlider.setShowTicks(true);
  speedSlider.setNumberFormat(G4P.DECIMAL, 2);
  speedSlider.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  speedSlider.setOpaque(false);
  speedSlider.addEventHandler(this, "speedChanged");
  flightCommandWindow.loop();
  PlaneWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow flightCommandWindow;
GButton startButton; 
GLabel label1; 
GButton clearFlights; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GDropList departureList; 
GDropList arrivalList; 
GButton addPlane; 
GTextArea informationBox; 
GLabel label5; 
GButton pauseButton; 
GPanel panel1; 
GWindow PlaneWindow;
GLabel selectedPlaneTitle; 
GLabel label6; 
GCheckbox togglePath; 
GCheckbox toggleTrail; 
GCheckbox toggleR; 
GCheckbox togglePlane; 
GSlider speedSlider; 
